"""Demo publisher keys: the *private* halves, on purpose.

In production a Compound tool publisher signs its manifest entry with a key
AuditPledge never sees; AuditPledge only holds the public half
(`data/keyring.json`). The offline demo has no such publisher, so this module
derives a deterministic Ed25519 keypair per demo publisher and signs the demo
catalogue with it.

That is a demo shortcut, and it is stated plainly here and in HONESTY.md. What
it buys is not fake: the signatures in the demo catalogue are genuine Ed25519
signatures over the canonical tool bytes, so the verification path in
`provenance.py` is doing real cryptography, and editing one character of the
catalogue makes the audit flip that tool to unsigned. Nothing in the verifier
imports this module.

    python -m auditpledge.demo_keys --write-keyring   # regenerate data/keyring.json
    python -m auditpledge.demo_keys                   # print the public keyring
"""

from __future__ import annotations

import hashlib
import json
import sys
from typing import Any

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from .provenance import KEYRING_PATH, canonical_bytes, normalize_publisher

_SEED_DOMAIN = b"auditpledge/demo-publisher-key/v1:"

# Publishers that hold a signing key in the demo world, seeded from the kind of
# roots the Compound community can vet. `defi-rando` deliberately has none: that
# is the unsigned, untrusted publisher the audit must catch.
DEMO_PUBLISHERS = ("compound-finance", "compound-community", "openzeppelin")


def private_key(publisher: str) -> Ed25519PrivateKey:
    seed = hashlib.sha256(_SEED_DOMAIN + normalize_publisher(publisher).encode()).digest()
    return Ed25519PrivateKey.from_private_bytes(seed)


def public_key_hex(publisher: str) -> str:
    raw = private_key(publisher).public_key().public_bytes(
        encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
    )
    return raw.hex()


def sign_tool(tool: dict[str, Any]) -> str:
    """Detached hex Ed25519 signature over the tool's canonical bytes."""
    return private_key(tool["publisher"]).sign(canonical_bytes(tool)).hex()


def public_keyring() -> dict[str, str]:
    return {normalize_publisher(p): public_key_hex(p) for p in DEMO_PUBLISHERS}


def write_keyring() -> str:
    KEYRING_PATH.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "note": "Public Ed25519 keys only. Generated by auditpledge.demo_keys for the "
                "offline demo catalogue; real deployments load their publishers' real keys.",
        "algorithm": "ed25519",
        "signed_fields": ["name", "version", "publisher", "scopes", "ops"],
        "publishers": public_keyring(),
    }
    KEYRING_PATH.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return str(KEYRING_PATH)


if __name__ == "__main__":
    if "--write-keyring" in sys.argv:
        print(f"wrote {write_keyring()}")
    else:
        print(json.dumps(public_keyring(), indent=2, sort_keys=True))
