"""Capture a real audit run and inject it into the offline UI page.

    python -m auditpledge.ui_data --write     # re-capture and rewrite ui/index.html
    python -m auditpledge.ui_data             # print the snapshot as JSON

`ui/index.html` is a single static file with no backend, so a reviewer can open
it offline. That makes it the easiest place in the repo to paint numbers that the
code does not produce. It therefore contains no hand-written numbers at all: the
tool list, the severities, the counters, the activity log, the pricing, the
counterfactual repricing and the downloadable report are all captured from one
actual `auditpledge audit --server compound-position-agent --source mcp --no-llm`
run against the bundled MCP stdio server, and pasted between the SNAPSHOT markers.

The page labels itself a recorded replay, and `tests/test_ui_snapshot.py` re-runs
the audit and fails if any of those values drift from what the code produces.
"""

from __future__ import annotations

import asyncio
import json
import re
import sys
from pathlib import Path
from typing import Any

UI_PATH = Path(__file__).with_name("ui") / "index.html"
BEGIN = "/* --- BEGIN SNAPSHOT (generated by: python -m auditpledge.ui_data --write) --- */"
END = "/* --- END SNAPSHOT --- */"

DEMO_SERVER = "compound-position-agent"
DEMO_SOURCE = "mcp"
DEMO_COMMAND = f"auditpledge audit --server {DEMO_SERVER} --source {DEMO_SOURCE} --no-llm"

# Values that legitimately change every run. Excluded from the drift check.
VOLATILE_KEYS = {"generated_at", "retrieved_at", "ms", "run_id", "transport", "captured_at"}
_RUN_RE = re.compile(r"run-\d{8}T\d{6}-[0-9a-f]+")
_TS_RE = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+00:00")
# The stdio transport command line names whatever interpreter launched it.
_PY_RE = re.compile(r"\S*python[0-9.]*(?=\s|$)")


def build_snapshot() -> dict[str, Any]:
    """Run the audit for real and package what the page needs to render it."""
    from agent_core import StateStore

    from .config import settings
    from .main import audit, format_report

    store = StateStore.create(settings)
    out = asyncio.run(audit(DEMO_SERVER, use_llm=False, source=DEMO_SOURCE, store=store))
    rep = out["report"]
    losses = {d["tool"]: d for d in rep["pricing"]["per_tool"]}

    tools = []
    for t in rep["assessment"]["tools"]:
        loss = losses.get(t["name"], {})
        tools.append({
            "name": t["name"],
            "publisher": t["publisher"],
            "severity": t["severity"],
            "score": t["score"],
            "signed": t["signed"],
            "trusted": t["trusted"],
            "rce_capable": t["rce_capable"],
            "position_exposed": t["position_exposed"],
            "findings": t["findings"],
            "expected_loss_usd": loss.get("expected_loss_usd", 0),
            "p_compromise": loss.get("p_compromise", 0),
            "p_driver": loss.get("p_driver", ""),
        })

    return {
        "captured_at": rep["generated_at"],
        "command": DEMO_COMMAND,
        "server": rep["server"],
        "synthetic_catalogue": rep["synthetic_catalogue"],
        "evidence": rep["evidence"],
        "counts": rep["assessment"]["counts"],
        "advisory_source": rep["assessment"]["advisory_source"],
        "simulated_advisories_counted": rep["assessment"]["simulated_advisories_counted"],
        "worst": rep["assessment"]["worst"]["name"] if rep["assessment"]["worst"] else None,
        "tools": tools,
        "pricing": rep["pricing"],
        "counterfactual": rep["counterfactual"],
        "trace": rep["trace"],
        "cli_text": format_report(out),
    }


def comparable(snapshot: dict[str, Any]) -> Any:
    """Strip the parts that change every run, so drift is the only thing left.

    Wall-clock timings, ISO timestamps, run IDs and the absolute interpreter path
    in the transport line all move between machines. Everything else - tool
    names, severities, scores, findings, counters, dollars, trace steps - must
    match the code exactly.
    """

    def strip(node: Any) -> Any:
        if isinstance(node, dict):
            return {k: strip(v) for k, v in sorted(node.items()) if k not in VOLATILE_KEYS}
        if isinstance(node, list):
            return [strip(v) for v in node]
        if isinstance(node, str):
            return _PY_RE.sub("<python>", _TS_RE.sub("<ts>", _RUN_RE.sub("<run>", node)))
        return node

    out = strip(snapshot)
    # Two lines of the CLI text describe the machine rather than the audit: the
    # transport command line (interpreter path) and the run footer (which state
    # backend was available). Drop those, keep every finding and every dollar.
    text = out.get("cli_text")
    if isinstance(text, str):
        out["cli_text"] = "\n".join(
            l for l in text.splitlines()
            if not l.startswith("  evidence: ") and not l.startswith("-- run="))
    return out


def read_embedded(path: Path | None = None) -> dict[str, Any]:
    """Parse the snapshot currently embedded in the UI page."""
    html = (path or UI_PATH).read_text(encoding="utf-8")
    start = html.find(BEGIN)
    end = html.find(END)
    if start < 0 or end < 0:
        raise ValueError(f"{path or UI_PATH} has no SNAPSHOT markers")
    body = html[start + len(BEGIN):end].strip()
    body = body.removeprefix("var SNAPSHOT =").strip().rstrip(";").strip()
    return json.loads(body)


def write(path: Path | None = None) -> str:
    p = path or UI_PATH
    html = p.read_text(encoding="utf-8")
    start = html.find(BEGIN)
    end = html.find(END)
    if start < 0 or end < 0:
        raise ValueError(f"{p} has no SNAPSHOT markers")
    payload = json.dumps(build_snapshot(), indent=2, sort_keys=True)
    new = html[:start] + BEGIN + "\nvar SNAPSHOT = " + payload + ";\n" + html[end:]
    p.write_text(new, encoding="utf-8")
    return str(p)


if __name__ == "__main__":
    if "--write" in sys.argv:
        print(f"wrote {write()}")
    else:
        print(json.dumps(build_snapshot(), indent=2, sort_keys=True))
